export const FORGOT_PASSWORD_CONSTANTS = {
    EMAIL_LABEL: "Email đăng ký",
    EMAIL_PLACEHOLDER: "Nhập email của bạn",
    OTP_LABEL: "Mã xác thực OTP (6 chữ số)",
    OTP_PLACEHOLDER: "Nhập mã OTP (Mã thử nghiệm: 123456)",
    NEW_PASSWORD_LABEL: "Mật khẩu mới",
    NEW_PASSWORD_PLACEHOLDER: "Nhập mật khẩu mới (tối thiểu 6 ký tự)",
    CONFIRM_PASSWORD_LABEL: "Xác nhận mật khẩu mới",
    CONFIRM_PASSWORD_PLACEHOLDER: "Nhập lại mật khẩu mới",
    SEND_OTP_BUTTON: "Gửi mã xác thực",
    SUBMIT_BUTTON: "Xác nhận đổi mật khẩu",
    BACK_TO_LOGIN: "Quay lại đăng nhập",

    REQUIRED_EMAIL: "Vui lòng nhập email.",
    INVALID_EMAIL: "Sai định dạng email. Ví dụ: tennguoidung@example.com",
    REQUIRED_OTP: "Vui lòng nhập mã OTP.",
    INVALID_OTP: "Mã OTP phải gồm 6 chữ số.",
    REQUIRED_NEW_PASSWORD: "Vui lòng nhập mật khẩu mới.",
    MIN_PASSWORD_LENGTH: "Mật khẩu phải có ít nhất 6 ký tự.",
    REQUIRED_CONFIRM_PASSWORD: "Vui lòng xác nhận mật khẩu.",
    PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp.",
} as const;
