export const REGISTER_CONSTANTS = {
    FULL_NAME_LABEL: "Họ và tên",
    FULL_NAME_PLACEHOLDER: "Ví dụ: Nguyễn Văn A",
    USERNAME_LABEL: "Tên đăng nhập",
    USERNAME_PLACEHOLDER: "Nhập tên đăng nhập (ví dụ: nguyenvana)",
    EMAIL_LABEL: "Địa chỉ Email",
    EMAIL_PLACEHOLDER: "Nhập email của bạn",
    PASSWORD_LABEL: "Mật khẩu",
    PASSWORD_PLACEHOLDER: "Tạo mật khẩu (tối thiểu 6 ký tự)",
    CONFIRM_PASSWORD_LABEL: "Xác nhận mật khẩu",
    CONFIRM_PASSWORD_PLACEHOLDER: "Nhập lại mật khẩu",
    SUBMIT_BUTTON: "Đăng ký tài khoản",
    LOGIN_LINK: "Đăng nhập ngay",
    HAVE_ACCOUNT: "Đã có tài khoản?",

    REQUIRED_FULL_NAME: "Vui lòng nhập họ và tên.",
    MIN_FULL_NAME: "Họ và tên phải có ít nhất 2 ký tự.",
    REQUIRED_USERNAME: "Vui lòng nhập tên đăng nhập.",
    MIN_USERNAME: "Tên đăng nhập phải có ít nhất 3 ký tự.",
    INVALID_USERNAME: "Tên đăng nhập chỉ được chứa chữ cái, số, gạch dưới (_) hoặc gạch ngang (-).",
    REQUIRED_EMAIL: "Vui lòng nhập email.",
    INVALID_EMAIL: "Sai định dạng email. Ví dụ: tennguoidung@example.com",
    REQUIRED_PASSWORD: "Vui lòng nhập mật khẩu.",
    MIN_PASSWORD: "Mật khẩu phải có ít nhất 6 ký tự.",
    REQUIRED_CONFIRM_PASSWORD: "Vui lòng xác nhận lại mật khẩu.",
    PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp.",
} as const;
